/* eslint-disable camelcase */
/* eslint-disable indent */
/* eslint-disable max-len */
const { mailFormatDate } = require('./date');
const { auditToolVersion, promToolVersion } = require('../../config/config');

const htmlTemplate = (
  {
    auditId,
    projName,
    projectID,
    auditStartDate,
    auditEndDate,
    auditTeamMembersNames,
    auditStatus,
    auditorName,
    work_package,
    instance,
    verified_by,
    checklistType,
    description,
    nonCompliances,
    noOfApplicableChecks,
    processComplianceIndex,
  },
  typeOfMail,
) => {
  let footerMessage;
  let preHeader;
  switch (typeOfMail) {
    case 'initiate':
      preHeader = 'Audit Has Been Initiated';
      footerMessage = `<br /> Quality Team has initiated ${checklistType} Audit for the project. <br />
                      All the best to all. <br />`;
      break;
    case 'closed':
      preHeader = 'Audit Has Been closed';
      footerMessage = `<br />  Quality Team has closed ${checklistType} Audit for the project.
                       Audit Report is attached in this email. <br />
                       Thank you all for your kind co-operation during Audit. <br />`;
      break;
    case 'draft':
      preHeader = 'Audit Report is Attached';
      footerMessage = `<br />  ${checklistType} Audit Report is attached in this email. <br />
                      All the best to all. <br />`;
      break;
    case 'notClosed':
      preHeader = 'Audit is Not closed';
      footerMessage = `<br />  ${checklistType} Audit closure date is nearing.
       No action is performed on this Audit. Need your kind attention. <br />
                      All the best to all. <br />`;
      break;
    case 'dateCrossed':
      preHeader = 'Audit closure date is crossed';
      footerMessage = `<br />  ${checklistType} Audit closure date is crossed.
       No action is performed on this Audit. Need your kind attention. <br />
                      All the best to all. <br />`;
      break;
    case 'update':
      preHeader = 'Audit updated';
      footerMessage = `<br />  ${checklistType} Audit is updated.
        Audit Report is attached in this email. <br />
        All the best to all. <br />`;
      break;
    default:
      footerMessage = 'Thank you all for your kind co-operation during Audit.';
  }
  const workPackage =
    work_package === null || work_package === ''
      ? ''
      : `<tr>
  <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Work Package:</th>
  <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${work_package}</th>
</tr>`;

  return `<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <head>
      
  </head>
  
  <body>
      <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">${preHeader}</span>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
          <tr>
              <td>&nbsp;</td>
              <!-- class="container" -->
  
              <td class="container">
                  <div class="content">
                      <div class="mainContent">
  
                          <!-- START CENTERED WHITE CONTAINER -->
  
                          <table role="presentation" class="main" style="border-collapse: collapse;">
                              <div>
                                  
                                  <div class="message" style="text-align: center;">
                                      ********************************************************************************
                                      <br>
                                      This email is auto generated by Audit Tool <br>
                                      ********************************************************************************
                                  </div>
                                  <br>
                                  Greetings!!!
                                  <br>
                                  <table role="presentation" class="mainTable" width="100%" style="margin-left: auto; margin-right: auto; width: 100%; max-width: 100%; border-collapse: collapse;">
                                      <tbody class="tablebody">
                                      <tr>
                                      <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Audit Id:</th>
                                      <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${auditId}</th>
                                        </tr>
                                         <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Project ID:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${projectID}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Project Name:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${projName}</th>
                                          </tr>
                                           <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Checklist Type:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${checklistType}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Instance:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${instance}</th>
                                          </tr>
                                            ${workPackage}
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Auditor Name:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${auditorName}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Audit Start Date:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${mailFormatDate(
    auditStartDate,
  )}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Audit Closure Date:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${mailFormatDate(
    auditEndDate,
  )}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Audit Team:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${auditTeamMembersNames}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Audit Status:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${auditStatus}</th>
                                          </tr>         
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Verified By:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${verified_by}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Description:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${description}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Non Compliances:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${nonCompliances}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">No.Of Applicable Checks:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${noOfApplicableChecks}</th>
                                          </tr>
                                          <tr>
                                          <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Process Compliance Index:</th>
                                          <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${processComplianceIndex}</th>
                                      </tr>
                                      </tbody>
                                  </table>
                                    <div class="message" style="text-align: center;">
                                      ${footerMessage}
                                      ********************************************************************************
                                      <br>
                                      Thank you for using Audit Tool ${auditToolVersion} <br>
                                      ********************************************************************************
                                      <br>
                                  </div>
                              </div>
                      </table></div>
      </div></td></tr></table>
      
      
      <td>&nbsp;</td>
      
      
  </body>
  </html>`;
};

const htmlTemplateForCostCenter = (
  {
    auditId,
    auditStartDate,
    auditEndDate,
    auditTeamMembersNames,
    auditStatus,
    costCenterCode,
    costCenterName,
    auditorName,
    work_package,
    instance,
    verified_by,
    checklistType,
    description,
  },
  typeOfMail,
) => {
  let footerMessage;
  let preHeader;
  switch (typeOfMail) {
    case 'initiate':
      preHeader = 'Audit Has Been Initiated';
      footerMessage = `<br /> Quality Team has initiated ${checklistType} Audit for the project. <br />
                      All the best to all. <br />`;
      break;
    case 'closed':
      preHeader = 'Audit Has Been closed';
      footerMessage = `<br />  Quality Team has closed ${checklistType} Audit for the project.
                       Audit Report is attached in this email. <br />
                       Thank you all for your kind co-operation during Audit. <br />`;
      break;
    case 'draft':
      preHeader = 'Audit Report is Attached';
      footerMessage = `<br />  ${checklistType} Audit Report is attached in this email. <br />
                      All the best to all. <br />`;
      break;
    case 'notClosed':
      preHeader = 'Audit is Not closed';
      footerMessage = `<br />  ${checklistType} Audit closure date is nearing.
       No action is performed on this Audit. Need your kind attention. <br />
                      All the best to all. <br />`;
      break;
    case 'update':
      preHeader = 'Audit updated';
      footerMessage = `<br />  ${checklistType} Audit is updated.
        Audit Report is attached in this email. <br />
        All the best to all. <br />`;
      break;
    case 'dateCrossed':
      preHeader = 'Audit date crossed';
      footerMessage = `<br />  ${checklistType} Audit closure date is crossed.
       No action is performed on this Audit. Need your kind attention. <br />
                      All the best to all. <br />`;
      break;
    default:
      footerMessage = 'Thank you all for your kind co-operation during Audit.';
  }
  const workPackage =
    work_package === null || work_package === undefined || work_package === ''
      ? ''
      : `<tr>
  <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Work Package:</th>
  <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${work_package}</th>
</tr>`;

  return `<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <head>
      
  </head>
  
  <body>
      <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">${preHeader}</span>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
          <tr>
              <td>&nbsp;</td>
              <!-- class="container" -->
  
              <td class="container">
                  <div class="content">
                      <div class="mainContent">
  
                          <!-- START CENTERED WHITE CONTAINER -->
  
                          <table role="presentation" class="main" style="border-collapse: collapse;">
                              <div>
                                  
                                  <div class="message" style="text-align: center;">
                                      ********************************************************************************
                                      <br>
                                      This email is auto generated by Audit Tool <br>
                                      ********************************************************************************
                                  </div>
                                  <br>
                                  Greetings!!!
                                  <br>
                                  <table role="presentation" class="mainTable" width="100%" style="margin-left: auto; margin-right: auto; width: 100%; max-width: 100%; border-collapse: collapse;">
                                      <tbody class="tablebody">
                                      <tr>
                                      <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Audit Id:</th>
                                      <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${auditId}</th>
                                        </tr>
                                         <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Cost Centre Code:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${costCenterCode}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Cost Centre Name:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${costCenterName}</th>
                                          </tr>
                                           <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Checklist Type:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${checklistType}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Instance:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${instance}</th>
                                          </tr>
                                            ${workPackage}
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Auditor Name:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${auditorName}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Audit Start Date:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${mailFormatDate(
    auditStartDate,
  )}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Audit Closure Date:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${mailFormatDate(
    auditEndDate,
  )}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Audit Team:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${auditTeamMembersNames}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Audit Status:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${auditStatus}</th>
                                          </tr>         
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Verified By:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${verified_by}</th>
                                          </tr>
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Description:</th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${description}</th>
                                          </tr>
                                      </tbody>
                                  </table>
                                    <div class="message" style="text-align: center;">
                                      ${footerMessage}
                                      ********************************************************************************
                                      <br>
                                      Thank you for using Audit Tool ${auditToolVersion} <br>
                                      ********************************************************************************
                                      <br>
                                  </div>
                              </div>
                      </table></div>
      </div></td></tr></table>
      
      
      <td>&nbsp;</td>
      
      
  </body>
  </html>`;
};

const sendDraftMailOptions = (auditInfo, auditorName, auditTeamData, updatedSubStatus) => {
  const requiredMailData = {
    auditId: auditInfo.auditId,
    projName: auditInfo.projectData.project_name,
    projectID: auditInfo.project_id,
    auditStartDate: auditInfo.audit_start_date,
    auditEndDate: auditInfo.audit_end_date,
    auditTeamMembersNames: auditTeamData,
    auditStatus: auditInfo.status,
    auditorName,
    checklistType: auditInfo.masterCheckList.type,
    description: auditInfo.description,
    verified_by: auditInfo.verified_by,
    instance: auditInfo.instance,
    work_package: auditInfo.work_package,
    // meetingData
  };

  const mailText = {
    subject: updatedSubStatus === 'FinalReportSent' ? 'Audit Report Final' : 'Audit Report Draft',
    text: 'Please Check Below the Updated Audit Details',
    html: htmlTemplate(requiredMailData, 'draft'),
  };
  return mailText;
};
const sendDraftMailOptionsForCostCenter = (auditInfo, auditorName, auditTeamData, updatedSubStatus) => {
  const requiredMailData = {
    auditId: auditInfo.auditId,
    costCenterCode: auditInfo.costCenterCode,
    costCenterName: auditInfo.costCenterName,
    auditStartDate: auditInfo.audit_start_date,
    auditEndDate: auditInfo.audit_end_date,
    auditTeamMembersNames: auditTeamData,
    auditStatus: auditInfo.status,
    auditorName,
    checklistType: auditInfo.masterCheckList.type,
    description: auditInfo.description,
    verified_by: auditInfo.verified_by,
    instance: auditInfo.instance,
    work_package: auditInfo.work_package,
  };

  const mailText = {
    subject: updatedSubStatus === 'FinalReportSent' ? 'Audit Report Final' : 'Audit Report Draft',
    text: 'Please Check Below the Updated Audit Details',
    html: htmlTemplateForCostCenter(requiredMailData, 'draft'),
  };
  return mailText;
};

const sendInitiateMail = (requiredMailData) => {
  const mailType = 'initiate';
  const initiateMail = {
    subject: ' Audit Initiated Mail',
    text: 'Initiate Mail',
    html: htmlTemplate(requiredMailData, mailType),
  };
  return initiateMail;
};

const sendInitiateMailForCostCentre = (requiredMailData) => {
  const mailType = 'initiate';
  const initiateMail = {
    subject: ' Audit Initiated Mail',
    text: 'Initiate Mail',
    html: htmlTemplateForCostCenter(requiredMailData, mailType),
  };
  return initiateMail;
};

const calenderMailingDataForCostCentre = (requiredMailData) => {
  const { inviteData } = requiredMailData;
  const mailType = 'initiate';
  const calenderMail = {
    text: 'Calender Mail',
    subject: `Audit Brief Meeting scheduled on ${inviteData.meetingDate}, from ${inviteData.meetingStartTime} to ${inviteData.meetingEndTime}.`,
    html: htmlTemplateForCostCenter(requiredMailData, mailType),
  };
  return calenderMail;
};
const calenderMailingData = (requiredMailData) => {
  const { inviteData } = requiredMailData;
  const mailType = 'initiate';
  const calenderMail = {
    text: 'Calender Mail',
    subject: `Audit Brief Meeting scheduled on ${inviteData.meetingDate}, from ${inviteData.meetingStartTime} to ${inviteData.meetingEndTime}.`,
    html: htmlTemplate(requiredMailData, mailType),
  };
  return calenderMail;
};

const sendClosedMail = (auditData) => {
  const mailType = 'closed';
  const closedMail = {
    subject: ' Audit Closed Mail',
    text: 'Closed Mail',
    html: htmlTemplate(auditData, mailType),
  };
  return closedMail;
};

const sendClosedMailForCostCenter = (auditData) => {
  const mailType = 'closed';
  const closedMail = {
    subject: ' Audit Closed Mail',
    text: 'Closed Mail',
    html: htmlTemplateForCostCenter(auditData, mailType),
  };
  return closedMail;
};

const sendAuditUpdatesMail = (auditData) => {
  const mailType = 'update';
  const closedMail = {
    subject: ' Audit Update Mail',
    text: 'update Mail',
    html: htmlTemplate(auditData, mailType),
  };
  return closedMail;
};

const sendAuditUpdatesMailForCostCenter = (auditData) => {
  const mailType = 'update';
  const closedMail = {
    subject: ' Audit Update Mail',
    text: 'update Mail',
    html: htmlTemplateForCostCenter(auditData, mailType),
  };
  return closedMail;
};
const auditNotClosed = (auditData, customMailForCrossedDate) => {
  const mailType = customMailForCrossedDate === true ? 'dateCrossed' : 'notClosed';
  const closedMail = {
    subject: customMailForCrossedDate === true ? 'Audit closure date crossed' : 'Audit not closed',
    text: customMailForCrossedDate === true ? 'Audit closure date crossed' : 'Audit not closed Mail',
    html: htmlTemplate(auditData, mailType),
  };
  return closedMail;
};

const auditNotClosedForCostCenter = (auditData, customMailForCrossedDate) => {
  const mailType = customMailForCrossedDate === true ? 'dateCrossed' : 'notClosed';
  const closedMail = {
    subject: customMailForCrossedDate === true ? 'Audit date crossed' : 'Audit not closed',
    text: customMailForCrossedDate === true ? 'Audit date crossed' : 'Audit not closed Mail',
    html: htmlTemplateForCostCenter(auditData, mailType),
  };
  return closedMail;
};
const forgotPasswordTemplate = (url, userName) => {
  const hyperLink = url;

  return `<!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <title>Audit Tool</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
  @media screen {
    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 400;
      src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'),
              url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff)
                format('woff');
    }
  
    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 700;
      src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'),
              url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff)
                format('woff');
    }
  }
  </style>
    </head>
    <body style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #e9ecef; width: 100%; height: 100%; padding: 0; margin: 0;">
      <div class="preheader" style="
          display: none;
          max-width: 0;
          max-height: 0;
          overflow: hidden;
          font-size: 1px;
          line-height: 1px;
          color: #fff;
          opacity: 0;
        ">
        Please Change the Password
      </div>
  
      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
        <tr>
          <td align="center" bgcolor="#e9ecef" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;">
              <tr>
                <td align="center" valign="top" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 36px 24px;"></td>
              </tr>
            </table>
          </td>
        </tr>
  
        <tr>
          <td align="center" bgcolor="#e9ecef" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;">
              <tr>
                <td align="left" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 36px 24px 0; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif;">
                  <h1 style="
                      margin: 0;
                      font-size: 32px;
                      font-weight: 700;
                      letter-spacing: -1px;
                      line-height: 48px;
                    ">
                    Reset Your Password
                  </h1>
                </td>
              </tr>
            </table>
          </td>
        </tr>
  
        <tr>
          <td align="center" bgcolor="#e9ecef" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;">
              <tr>
                <td align="left" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
                  <p style="margin: 0">
                  Hey ${userName},<br>

                  There is a request to reset your password!<br>
                  If you did not make this request, please ignore the mail.<br>
                  
                  Otherwise, please click on the below button to reset your password.
                  
                  
                 
                  </p>
                </td>
              </tr>
  
              <tr>
                <td align="left" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
                  <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                    <tr>
                      <td align="center" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 12px;">
                        <table border="0" cellpadding="0" cellspacing="0" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                          <tr align="center" bgcolor="#ffffff" style="border-radius: 6px">
                            <td align="center" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-radius: 6px;">
                              <a href="${hyperLink}" target="_blank" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; display: inline-block; font-family: 'Source Sans Pro', Helvetica, Arial,
                                    sans-serif; font-size: 16px;">Reset Password</a>
                            </td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
  
              <tr>
                <td align="left" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
                  <p style="margin: 0">This reset password link is only VALID for the next 10 minutes.</p><br>
                  <p style="margin: 0">
                  Regards,<br>
                  AUDIT Tool<br>
                  
                  Note: This is a system generated email, please do not reply.
                    <!-- <a href="https://sendgrid.com" target="_blank"
                      >https://same-link-as-button.url/xxx-xxx-xxxx</a
                    > -->
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
  
        <tr>
          <td align="center" bgcolor="#e9ecef" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 24px;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;"></table>
          </td>
        </tr>
      </table>
    </body>
  </html>`;
};

const forgotPasswordMailData = (url, token, userName) => {
  const urlLink = `http://${url}/reset-password/${token}`;
  const forgotMail = {
    subject: 'Reset Password',
    text: 'forgot mail',
    html: forgotPasswordTemplate(urlLink, userName),
  };
  return forgotMail;
};

const promForgotPasswordTemplate = (url, userName) => {
  const hyperLink = url;
  return `<!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <title>Audit Tool</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
  @media screen {
    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 400;
      src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'),
              url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff)
                format('woff');
    }
  
    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 700;
      src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'),
              url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff)
                format('woff');
    }
  }
  </style>
    </head>
    <body style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #e9ecef; width: 100%; height: 100%; padding: 0; margin: 0;">
      <div class="preheader" style="
          display: none;
          max-width: 0;
          max-height: 0;
          overflow: hidden;
          font-size: 1px;
          line-height: 1px;
          color: #fff;
          opacity: 0;
        ">
        Please Change the Password
      </div>
  
      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
        <tr>
          <td align="center" bgcolor="#e9ecef" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;">
              <tr>
                <td align="center" valign="top" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 36px 24px;"></td>
              </tr>
            </table>
          </td>
        </tr>
  
        <tr>
          <td align="center" bgcolor="#e9ecef" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;">
              <tr>
                <td align="left" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 36px 24px 0; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif;">
                  <h1 style="
                      margin: 0;
                      font-size: 32px;
                      font-weight: 700;
                      letter-spacing: -1px;
                      line-height: 48px;
                    ">
                    Reset Your Password
                  </h1>
                </td>
              </tr>
            </table>
          </td>
        </tr>
  
        <tr>
          <td align="center" bgcolor="#e9ecef" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;">
              <tr>
                <td align="left" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
                  <p style="margin: 0">
                  Hey ${userName},<br>

                  There is a request to reset your password!<br>
                  If you did not make this request, please ignore the mail.<br>
                  
                  Otherwise, please click on the below button to reset your password.
                  
                  
                 
                  </p>
                </td>
              </tr>
  
              <tr>
                <td align="left" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
                  <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                    <tr>
                      <td align="center" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 12px;">
                        <table border="0" cellpadding="0" cellspacing="0" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
                          <tr align="center" bgcolor="#ffffff" style="border-radius: 6px">
                            <td align="center" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-radius: 6px;">
                              <a href="${hyperLink}" target="_blank" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; display: inline-block; font-family: 'Source Sans Pro', Helvetica, Arial,
                                    sans-serif; font-size: 16px;">Reset Password</a>
                            </td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
  
              <tr>
                <td align="left" bgcolor="#ffffff" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
                  <p style="margin: 0">This reset password link is only VALID for the next 10 minutes.</p><br>
                  <p style="margin: 0">
                  Regards,<br>
                  RM Tool<br>
                  
                  Note: This is a system generated email, please do not reply.
                    <!-- <a href="https://sendgrid.com" target="_blank"
                      >https://same-link-as-button.url/xxx-xxx-xxxx</a
                    > -->
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
  
        <tr>
          <td align="center" bgcolor="#e9ecef" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 24px;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;"></table>
          </td>
        </tr>
      </table>
    </body>
  </html>`;
};

const promForgotPasswordMailData = (url, token, userName) => {
  const urlLink = `http://${url}/reset-password/${token}`;
  const forgotMail = {
    subject: 'Reset Password',
    text: 'forgot mail',
    html: promForgotPasswordTemplate(urlLink, userName),
  };
  return forgotMail;
};

const aprrovalMail = (request) => {
  const footerMessage = 'Please do not reply to this mail as it is auto generated mail.';
  return `<html>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <head>
        
    </head>
    
    <body>
        <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
            <tr>
                <td>&nbsp;</td>
                <!-- class="container" -->
    
                <td class="container">
                    <div class="content">
                        <div class="mainContent">
    
                            <!-- START CENTERED WHITE CONTAINER -->
    
                            <table role="presentation" class="main" style="border-collapse: collapse;">
                                <div>
                                    
                                    <div class="message" style="text-align: center;">
                                        ********************************************************************************
                                        <br> This email is auto generated by RM Tool <br>
                                        ********************************************************************************
                                    </div>
                                    <br>
                                    Greetings!!! <br>
                                    <br>
                                    <table role="presentation" class="mainTable" width="100%" style="margin-left: auto; margin-right: auto; width: 100%; max-width: 100%; border-collapse: collapse;">
                                        <tbody class="tablebody">
                                            <tr>
                                                <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Project Name:</th>
                                                <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${request.projName
    }</th>
                                            </tr>
                                            <tr>
                                                <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Project ID:</th>
                                                <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${request.project_code
    }</th>
                                            </tr>
                                            <tr>
                                                <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Claim Request By:</th>
                                                <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${request.resource_emp_id
    }</th>
                                            </tr>
                                            <tr>
                                                <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Claim Request Date:</th>
                                                <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${mailFormatDate(
      request.date,
    )}</th>
                                            </tr>
                                            <tr>
                                                <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Claim Type:</th>
                                                <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${request.expense_type
    }</th>
                                            </tr>
                                            <tr>
                                            <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Claim Amount:</th>
                                            <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${request.amount
    }</th>
                                        </tr>
                                            <tr>
                                                <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left">Claim Status:</th>
                                                <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${request.claimStatus
    }</th>
                                            </tr>
                                        </tbody>
                                    </table>
                                      <div class="message" style="text-align: center;">
                                        ${footerMessage}<br>
                                        ********************************************************************************
                                        <br>
                                        Thank you for using RM Tool  ${promToolVersion} <br>
                                        ********************************************************************************
                                        <br>
                                    </div>
                                </div>
                        </table></div>
        </div></td></tr></table>
        
        
        <td>&nbsp;</td>
        
        
    </body>
    </html>`;
};

const sendIAprrovalRequestMail = (request) => {
  let subContent;
  if (request.claimStatus === 'Raised') {
    subContent = `Claim Request: ${request.employeeName} – ${request.resource_emp_id}`;
  } else subContent = `Claim Approval: ${request.employeeName} – ${request.resource_emp_id}`;
  const aprrovalRequestMail = {
    subject: subContent,
    text: 'claims approval mail',
    html: aprrovalMail(request),
  };
  return aprrovalRequestMail;
};

const rolesModificationMailUpdate = (roles, userName, toolName, roleAdded, rolesRemoved) => {
  let message;
  if (roleAdded) {
    message = `This is to inform you that, you are being assigned to ${roles} group by Admin in the ${toolName}.<br>`;
  } else if (rolesRemoved) {
    message = `This is to inform you that, you have been removed from ${roles} group by Admin in the ${toolName}.<br>`;
  }

  const roleModificationhtml = `<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>${toolName}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
        @media screen {
            @font-face {
                font-family: 'Source Sans Pro';
                font-style: normal;
                font-weight: 400;
                src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'),
                    url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff) format('woff');
            }

            @font-face {
                font-family: 'Source Sans Pro';
                font-style: normal;
                font-weight: 700;
                src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'),
                    url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff) format('woff');
            }
        }
    </style>
</head>

<body
    style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #e9ecef; width: 100%; height: 100%; padding: 0; margin: 0;">
    <div class="preheader" style="
          display: none;
          max-width: 0;
          max-height: 0;
          overflow: hidden;
          font-size: 1px;
          line-height: 1px;
          color: #fff;
          opacity: 0;
        ">
        Role is updated
    </div>

    <table border="0" cellpadding="0" cellspacing="0" width="100%"
        style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; border-collapse: collapse;">
        <tr>
            <td align="center" bgcolor="#e9ecef"
                style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%"
                    style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;">
                    <tr>
                        <td align="center" valign="top"
                            style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 36px 24px;">
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td align="center" bgcolor="#e9ecef"
                style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%"
                    style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;">
                    <tr>
                        <td align="left" bgcolor="#ffffff"
                            style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 10px 20px 0; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; border-top: 3px solid #115288;">

                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td align="center" bgcolor="#e9ecef"
                style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%"
                    style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;">
                    <tr>
                        <td align="left" bgcolor="#ffffff"
                            style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
                            <p style="margin: 0">
                                Dear ${userName ?? 'User'},<br>
                                Greetings!!!<br>
                                ${message}
                                Please contact Admin, if any concerns.
                            </p>
                        </td>
                    </tr>


                    <tr>
                        <td align="left" bgcolor="#ffffff"
                            style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
                            <p style="margin: 0">
                                Thanks and Regards.<br>
                                ${toolName}<br>

                                <br>
                                Note: This is a system generated email, please do not reply.
                                <!-- <a href="https://sendgrid.com" target="_blank"
                      >https://same-link-as-button.url/xxx-xxx-xxxx</a
                    > -->
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td align="center" bgcolor="#e9ecef"
                style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; padding: 24px;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%"
                    style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; mso-table-rspace: 0pt; mso-table-lspace: 0pt; max-width: 600px; border-collapse: collapse;">
                </table>
            </td>
        </tr>
    </table>
</body>

</html>
  `;

  const roleModificationData = {
    subject: 'Role has been Updated',
    text: 'Role Modified',
    html: roleModificationhtml,
  };
  return roleModificationData;
};

const managerMailingDataForPartialOrUnallocatedData = (managersEmployee, toolName) => {
  const footerMessage = 'Please do not reply to this mail as it is auto generated mail.';
  const preHeader = ' Employee details for the Next Month <br>';
  // add tool version in Footer of the Mail
  let toolVersionForMail;
  switch (toolName) {
    case 'Audit Tool':
      toolVersionForMail = auditToolVersion;
      break;
    case 'RM Tool':
      toolVersionForMail = promToolVersion;
      break;
    default:
      toolVersionForMail = 'draft';
  }

  let allocationTableData = ''; // mapping and not returning because it is adding extra comma into output
  managersEmployee.forEach(({ highestAllocationForMonth: allocation, employeeId, resource_name: resName }) => {
    allocationTableData += `<tr>
            <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${employeeId} </th>
            <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${resName} </th>
            <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${allocation?.toString()} </th>
             </tr>`;
  });

  const text = 'Employee Allocation Details';
  const subject = 'Employee allocation Details for next month';
  const customMessage = 'Below are details for partial/unallocated Employees for the next month';

  const managerHtmlData = `<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <head>
      
  </head>
  
  <body>
      <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">${preHeader}</span>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
          <tr>
              <td>&nbsp;</td>
              <!-- class="container" -->
  
              <td class="container">
                  <div class="content">
                      <div class="mainContent">
  
                          <!-- START CENTERED WHITE CONTAINER -->
  
                          <table role="presentation" class="main" style="border-collapse: collapse;">
                              <div>
                                  
                                  <div class="message" style="text-align: center;">
                                      ********************************************************************************
                                      <br>
                                      This email is auto generated by ${toolName} <br>
                                      ********************************************************************************
                                  </div>
                                  <br>
                                  Greetings!!! <br>
                                  <br>
                                  ${customMessage}
                                  <br>
                                  <br>
                                  <table role="presentation" class="mainTable" width="100%" style="margin-left: auto; margin-right: auto; width: 100%; max-width: 100%; border-collapse: collapse;">
                                      <tbody class="tablebody">
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Employee Id </th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Name </th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Allocation </th>
                                          </tr>
                                          ${allocationTableData}
                                          
                                          
                                      </tbody>
                                  </table>
                                    <div class="message" style="text-align: center;">
                                    <br>
                                      ${footerMessage}
                                      <br>
                                      <br>
                                      ********************************************************************************
                                      <br>
                                      Thank you for using ${toolName} ${toolVersionForMail} <br>
                                      ********************************************************************************
                                      <br>
                                  </div>
                              </div>
                      </table></div>
      </div></td></tr></table>
      <td>&nbsp;</td>    
  </body>
  </html>`;
  return { managerHtmlData, subject, text };
};

const managerMailingDataForPlannedActualResourceCount = (resourceMailData, toolName) => {
  const footerMessage = 'Please do not reply to this mail as it is auto generated mail.';
  const preHeader = ' Employee Planned and Actual details for the Current Month <br>';
  // add tool version in Footer of the Mail
  let toolVersionForMail;
  switch (toolName) {
    case 'Audit Tool':
      toolVersionForMail = auditToolVersion;
      break;
    case 'RM Tool':
      toolVersionForMail = promToolVersion;
      break;
    default:
      toolVersionForMail = 'draft';
  }

  let allocationTableData = ''; // mapping and not returning because it is adding extra comma into output
  resourceMailData.forEach(
    ({
      bu_name,
      project_code,
      project_name,
      project_manager_name,
      plannedResourceCount,
      actualResourceCount,
      actualAllocation,
      // highestAllocationForMonth: allocation, employeeId, resource_name: resName
    }) => {
      allocationTableData += `<tr>
            <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${bu_name} </th>
            <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${project_code} </th>
            <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${project_name} </th>
            <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${project_manager_name} </th>
            <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${plannedResourceCount} </th>
            <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${actualResourceCount} </th>
            <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${actualAllocation} </th>
            </tr>`;
    },
  );

  const text = 'Resource Planned and Actual Allocation Details';
  const subject = 'Resource Planned and Actual Allocation Details for current month';
  const customMessage = 'Below are details for planned & Actual Resources Allocation for the current month';

  const managerHtmlData = `<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <head>
      
  </head>
  
  <body>
      <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">${preHeader}</span>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
          <tr>
              <td>&nbsp;</td>
              <!-- class="container" -->
  
              <td class="container">
                  <div class="content">
                      <div class="mainContent">
  
                          <!-- START CENTERED WHITE CONTAINER -->
  
                          <table role="presentation" class="main" style="border-collapse: collapse;">
                              <div>
                                  
                                  <div class="message" style="text-align: center;">
                                      ********************************************************************************
                                      <br>
                                      This email is auto generated by ${toolName} <br>
                                      ********************************************************************************
                                  </div>
                                  <br>
                                  Greetings!!! <br>
                                  <br>
                                  ${customMessage}
                                  <br>
                                  <br>
                                  <table role="presentation" class="mainTable" width="100%" style="margin-left: auto; margin-right: auto; width: 100%; max-width: 100%; border-collapse: collapse;">
                                      <tbody class="tablebody">
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> BU Name </th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Project Code </th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Project Name </th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Project Manager Name </th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Planned Resource Count </th>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Actual Resource Count </th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Actual Allocation </th>
                                       
                                       
                                              </tr>
                                          ${allocationTableData}
                                          
                                          
                                      </tbody>
                                  </table>
                                    <div class="message" style="text-align: center;">
                                    <br>
                                      ${footerMessage}
                                      <br>
                                      <br>
                                      ********************************************************************************
                                      <br>
                                      Thank you for using ${toolName} ${toolVersionForMail} <br>
                                      ********************************************************************************
                                      <br>
                                  </div>
                              </div>
                      </table></div>
      </div></td></tr></table>
      <td>&nbsp;</td>    
  </body>
  </html>`;
  return { managerHtmlData, subject, text };
};

const managerMailingDataUnallocatedData = (managersEmployee, toolName) => {
  const footerMessage = 'Please do not reply to this mail as it is auto generated mail.';
  const preHeader = ' employee Moved to buffer project <br>';
  // add tool version in Footer of the Mail
  let toolVersionForMail;
  switch (toolName) {
    case 'Audit Tool':
      toolVersionForMail = auditToolVersion;
      break;
    case 'RM Tool':
      toolVersionForMail = promToolVersion;
      break;
    default:
      toolVersionForMail = 'draft';
  }

  let allocationTableData = ''; // mapping and not returning because it is adding extra comma into output
  managersEmployee.forEach(({ employeeId, resource_name: resName }) => {
    allocationTableData += `<tr>
            <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${employeeId} </th>
            <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${resName} </th>
             </tr>`;
  });

  const text = 'unallocated employee moved To Buffer project';
  const subject = 'Employees moved to buffer project by tool';
  const customMessage = 'Below are details of Employees which are moved to buffer project By the tool';

  const managerHtmlData = `<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <head>   
  </head>
  <body>
      <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">${preHeader}</span>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
          <tr>
              <td>&nbsp;</td>
              <!-- class="container" -->
  
              <td class="container">
                  <div class="content">
                      <div class="mainContent">
  
                          <!-- START CENTERED WHITE CONTAINER -->
  
                          <table role="presentation" class="main" style="border-collapse: collapse;">
                              <div>
                                  
                                  <div class="message" style="text-align: center;">
                                      ********************************************************************************
                                      <br>
                                      This email is auto generated by ${toolName} <br>
                                      ********************************************************************************
                                  </div>
                                  <br>
                                  Greetings!!! <br>
                                  <br>
                                  ${customMessage}
                                  <br>
                                  <br>
                                  <table role="presentation" class="mainTable" width="100%" style="margin-left: auto; margin-right: auto; width: 100%; max-width: 100%; border-collapse: collapse;">
                                      <tbody class="tablebody">
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Employee Id </th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Name </th>
                                          </tr>
                                          ${allocationTableData}
                                          
                                          
                                      </tbody>
                                  </table>
                                    <div class="message" style="text-align: center;">
                                    <br>
                                      ${footerMessage}
                                      <br>
                                      <br>
                                      ********************************************************************************
                                      <br>
                                      Thank you for using ${toolName} ${toolVersionForMail} <br>
                                      ********************************************************************************
                                      <br>
                                  </div>
                              </div>
                      </table></div>
      </div></td></tr></table>
      <td>&nbsp;</td>    
  </body>
  </html>`;
  return { managerHtmlData, subject, text };
};

const managerMailingDataForBufferEmployeeList = (managersEmployee, toolName) => {
  const footerMessage = 'Please do not reply to this mail as it is auto generated mail.';
  const preHeader = ' Employees in Buffer Project <br>';
  // add tool version in Footer of the Mail
  let toolVersionForMail;
  switch (toolName) {
    case 'Audit Tool':
      toolVersionForMail = auditToolVersion;
      break;
    case 'RM Tool':
      toolVersionForMail = promToolVersion;
      break;
    default:
      toolVersionForMail = 'draft';
  }

  let allocationTableData = ''; // mapping and not returning because it is adding extra comma into output
  managersEmployee.forEach(({ employeeId, resource_name: resName }) => {
    allocationTableData += `<tr>
            <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${employeeId} </th>
            <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${resName} </th>
             </tr>`;
  });

  const text = 'list of employee in buffer project';
  const subject = 'Employee in the buffer project';
  const customMessage = 'Below are details of Employees which are in buffer project';

  const managerHtmlData = `<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <head>
      
  </head>
  
  <body>
      <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">${preHeader}</span>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
          <tr>
              <td>&nbsp;</td>
              <!-- class="container" -->
  
              <td class="container">
                  <div class="content">
                      <div class="mainContent">
  
                          <!-- START CENTERED WHITE CONTAINER -->
  
                          <table role="presentation" class="main" style="border-collapse: collapse;">
                              <div>
                                  
                                  <div class="message" style="text-align: center;">
                                      ********************************************************************************
                                      <br>
                                      This email is auto generated by ${toolName} <br>
                                      ********************************************************************************
                                  </div>
                                  <br>
                                  Greetings!!! <br>
                                  <br>
                                  ${customMessage}
                                  <br>
                                  <br>
                                  <table role="presentation" class="mainTable" width="100%" style="margin-left: auto; margin-right: auto; width: 100%; max-width: 100%; border-collapse: collapse;">
                                      <tbody class="tablebody">
                                          <tr>
                                              <th class="tablestyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Employee Id </th>
                                              <th class="tableNextStyle" style="width: 70%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Name </th>
                                          </tr>
                                          ${allocationTableData}
                                          
                                          
                                      </tbody>
                                  </table>
                                    <div class="message" style="text-align: center;">
                                    <br>
                                      ${footerMessage}
                                      <br>
                                      <br>
                                      ********************************************************************************
                                      <br>
                                      Thank you for using ${toolName} ${toolVersionForMail} <br>
                                      ********************************************************************************
                                      <br>
                                  </div>
                              </div>
                      </table></div>
      </div></td></tr></table>
      <td>&nbsp;</td>    
  </body>
  </html>`;
  return { managerHtmlData, subject, text };
};

const managerMailingDataForPartialAllocatedResources = (managersEmployees, toolName) => {
  const footerMessage = 'Please do not reply to this mail as it is auto generated mail.';
  const preHeader = 'Partially Allocated Resorce details for the Next Month <br>';
  // add tool version in Footer of the Mail
  let toolVersionForMail;
  switch (toolName) {
    case 'Audit Tool':
      toolVersionForMail = auditToolVersion;
      break;
    case 'RM Tool':
      toolVersionForMail = promToolVersion;
      break;
    default:
      toolVersionForMail = 'draft';
  }

  let allocationTableData = ''; // mapping and not returning because it is adding extra comma into output
  managersEmployees.forEach(({ employeeId, resource_name, reporting_manager, highestAllocationForMonth }) => {
    allocationTableData += `<tr>
            <th class="tablestyle" style="width: 20%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${employeeId} </th>
            <th class="tableNextStyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${resource_name} </th>
            <th class="tableNextStyle" style="width: 40%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${reporting_manager} </th>
            <th class="tableNextStyle" style="width: 10%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${1 - highestAllocationForMonth
      } </th>
            </tr>`;
  });

  const text = 'Partially allocated Resource Details';
  const subject = 'Partially allocated Resource Details for the Next month';
  const customMessage = 'Partially allocated Resource Details for the Next month';

  const managerHtmlData = `<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <head>
      
  </head>
  
  <body>
      <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">${preHeader}</span>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
          <tr>
              <td>&nbsp;</td>
              <!-- class="container" -->
  
              <td class="container">
                  <div class="content">
                      <div class="mainContent">
  
                          <!-- START CENTERED WHITE CONTAINER -->
  
                          <table role="presentation" class="main" style="border-collapse: collapse;">
                              <div>
                                  
                                  <div class="message" style="text-align: center;">
                                      ********************************************************************************
                                      <br>
                                      This email is auto generated by ${toolName} <br>
                                      ********************************************************************************
                                  </div>
                                  <br>
                                  Greetings!!! <br>
                                  <br>
                                  ${customMessage}
                                  <br>
                                  <br>
                                  <table role="presentation" class="mainTable" width="100%" style="margin-left: auto; margin-right: auto; width: 100%; max-width: 100%; border-collapse: collapse;">
                                      <tbody class="tablebody">
                                          <tr>
                                              <th class="tablestyle" style="width: 20%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Employee ID </th>
                                              <th class="tableNextStyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Resource Name</th>
                                              <th class="tableNextStyle" style="width: 40%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Reporting manager </th>
                                              <th class="tableNextStyle" style="width: 10%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Allocation</th>
    
                                              </tr>
                                          ${allocationTableData}
                                          
                                          
                                      </tbody>
                                  </table>
                                    <div class="message" style="text-align: center;">
                                    <br>
                                      ${footerMessage}
                                      <br>
                                      <br>
                                      ********************************************************************************
                                      <br>
                                      Thank you for using ${toolName} ${toolVersionForMail} <br>
                                      ********************************************************************************
                                      <br>
                                  </div>
                              </div>
                      </table></div>
      </div></td></tr></table>
      <td>&nbsp;</td>    
  </body>
  </html>`;
  return { managerHtmlData, subject, text };
};


const allGroupHeadForPartialAllocatedResources = (managersEmployees, toolName) => {
  const footerMessage = 'Please do not reply to this mail as it is auto generated mail.';
  const preHeader = 'Partially Allocated Resorce details for the Next Month <br>';
  // add tool version in Footer of the Mail
  let toolVersionForMail;
  switch (toolName) {
    case 'Audit Tool':
      toolVersionForMail = auditToolVersion;
      break;
    case 'RM Tool':
      toolVersionForMail = promToolVersion;
      break;
    default:
      toolVersionForMail = 'draft';
  }

  let allocationTableData = ''; // mapping and not returning because it is adding extra comma into output
  managersEmployees.forEach(({ employeeId, resourceName, groupName, reportingManager, highestAllocationForMonth }) => {
    allocationTableData += `<tr>
            <th class="tablestyle" style="width: 15%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${employeeId} </th>
            <th class="tableNextStyle" style="width: 20%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${resourceName} </th>
            <th class="tableNextStyle" style="width: 25%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${groupName} </th>
            <th class="tableNextStyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${reportingManager} </th>
            <th class="tableNextStyle" style="width: 10%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> ${highestAllocationForMonth
      } </th>
            </tr>`;
  });

  const text = 'Following resource are moved to buffer as they are not allocated fully or allocated partially For the coming month.';
  const subject = 'Resources moved to buffer';
  const customMessage = 'All groups Partially allocated Resource Details for the Next month';

  const managerHtmlData = `<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <head>
      
  </head>
  
  <body>
      <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; visibility: hidden; width: 0;">${preHeader}</span>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
          <tr>
              <td>&nbsp;</td>
              <!-- class="container" -->
  
              <td class="container">
                  <div class="content">
                      <div class="mainContent">
  
                          <!-- START CENTERED WHITE CONTAINER -->
  
                          <table role="presentation" class="main" style="border-collapse: collapse;">
                              <div>
                                  
                                  <div class="message" style="text-align: center;">
                                      ********************************************************************************
                                      <br>
                                      This email is auto generated by ${toolName} <br>
                                      ********************************************************************************
                                  </div>
                                  <br>
                                  Greetings!!! <br>
                                  <br>
                                  ${customMessage}
                                  <br>
                                  <br>
                                  <table role="presentation" class="mainTable" width="100%" style="margin-left: auto; margin-right: auto; width: 100%; max-width: 100%; border-collapse: collapse;">
                                      <tbody class="tablebody">
                                          <tr>
                                              <th class="tablestyle" style="width: 15%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Employee ID </th>
                                              <th class="tableNextStyle" style="width: 20%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Resource Name</th>
                                              <th class="tableNextStyle" style="width: 25%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> BU Name </th>
                                              <th class="tableNextStyle" style="width: 30%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Reporting Manager</th>
                                              <th class="tableNextStyle" style="width: 10%; border: 1px solid #999; padding: 5px; text-align: left;" align="left"> Allocation</th>
    
                                              </tr>
                                          ${allocationTableData}
                                          
                                          
                                      </tbody>
                                  </table>
                                    <div class="message" style="text-align: center;">
                                    <br>
                                      ${footerMessage}
                                      <br>
                                      <br>
                                      ********************************************************************************
                                      <br>
                                      Thank you for using ${toolName} ${toolVersionForMail} <br>
                                      ********************************************************************************
                                      <br>
                                  </div>
                              </div>
                      </table></div>
      </div></td></tr></table>
      <td>&nbsp;</td>    
  </body>
  </html>`;
  return { managerHtmlData, subject, text };
};
module.exports = {
  calenderMailingDataForCostCentre,
  sendInitiateMailForCostCentre,
  sendDraftMailOptions,
  sendInitiateMail,
  calenderMailingData,
  sendClosedMail,
  auditNotClosed,
  forgotPasswordMailData,
  sendIAprrovalRequestMail,
  promForgotPasswordMailData,
  rolesModificationMailUpdate,
  managerMailingDataForPartialOrUnallocatedData,
  managerMailingDataUnallocatedData,
  managerMailingDataForBufferEmployeeList,
  sendAuditUpdatesMail,
  sendClosedMailForCostCenter,
  sendAuditUpdatesMailForCostCenter,
  auditNotClosedForCostCenter,
  sendDraftMailOptionsForCostCenter,
  managerMailingDataForPlannedActualResourceCount,
  managerMailingDataForPartialAllocatedResources,
  allGroupHeadForPartialAllocatedResources
};
